CREATE TABLE `directors` (
 `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
 `domain-id` int(11) UNSIGNED NOT NULL DEFAULT '0',
 `jump-id` int(11) UNSIGNED NOT NULL DEFAULT '0',
 `referee` varchar(500) NOT NULL DEFAULT '',
 `url` varchar(500) NOT NULL DEFAULT '',
 `focus-mining` int(11) UNSIGNED NOT NULL DEFAULT '0',
 `focus-ip-id` int(11) UNSIGNED NOT NULL DEFAULT '0',
 `focus-tld-id` int(11) UNSIGNED NOT NULL DEFAULT '0',
 `focus-url` varchar(500) NOT NULL DEFAULT '',
 `focus-title` varchar(200) NOT NULL DEFAULT '',
 `focus-sitename` varchar(200) NOT NULL DEFAULT '',
 `focus-decription` tinytext,
 `focus-keywords` tinytext,
 `focus-feed` varchar(200) NOT NULL DEFAULT '',
 `focus-image` varchar(200) NOT NULL DEFAULT '',
 `focus-icon` varchar(200) NOT NULL DEFAULT '',
 `focus-mimetype` varchar(100) NOT NULL DEFAULT '',
 `focus-email` varchar(200) NOT NULL DEFAULT '',
 `focus-generator` varchar(200) NOT NULL DEFAULT '',
 `uids` tinytext,
 `api-uid` int(11) UNSIGNED NOT NULL DEFAULT '0',
 `callback-hit` varchar(200) NOT NULL DEFAULT '',
 `callback-stats` varchar(200) NOT NULL DEFAULT '',
 `callback-reports` varchar(200) NOT NULL DEFAULT '',
 `callback-expiry` varchar(200) NOT NULL DEFAULT '',
 `last-ip-id` int(11) UNSIGNED NOT NULL DEFAULT '0',
 `hour-start` int(11) UNSIGNED NOT NULL DEFAULT '0',
 `hour-ended` int(11) UNSIGNED NOT NULL DEFAULT '0',
 `day-start` int(11) UNSIGNED NOT NULL DEFAULT '0',
 `day-ended` int(11) UNSIGNED NOT NULL DEFAULT '0',
 `week-start` int(11) UNSIGNED NOT NULL DEFAULT '0',
 `week-ended` int(11) UNSIGNED NOT NULL DEFAULT '0',
 `fortnight-start` int(11) UNSIGNED NOT NULL DEFAULT '0',
 `fortnight-ended` int(11) UNSIGNED NOT NULL DEFAULT '0',
 `month-start` int(11) UNSIGNED NOT NULL DEFAULT '0',
 `month-ended` int(11) UNSIGNED NOT NULL DEFAULT '0',
 `quarter-start` int(11) UNSIGNED NOT NULL DEFAULT '0',
 `quarter-ended` int(11) UNSIGNED NOT NULL DEFAULT '0',
 `year-start` int(11) UNSIGNED NOT NULL DEFAULT '0',
 `year-ended` int(11) UNSIGNED NOT NULL DEFAULT '0',
 `hits-total` int(11) NOT NULL DEFAULT '0',
 `hits-last` int(11) UNSIGNED NOT NULL DEFAULT '0',
 `hits-previous` int(11) UNSIGNED NOT NULL DEFAULT '0',
 `hits-oftern` float(21,10) UNSIGNED NOT NULL DEFAULT '0',
 `hits-hour` int(11) UNSIGNED NOT NULL DEFAULT '0',
 `hits-day` int(11) UNSIGNED NOT NULL DEFAULT '0',
 `hits-week` int(11) UNSIGNED NOT NULL DEFAULT '0',
 `hits-fortnight` int(11) UNSIGNED NOT NULL DEFAULT '0',
 `hits-month` int(11) UNSIGNED NOT NULL DEFAULT '0',
 `hits-quarter` int(11) UNSIGNED NOT NULL DEFAULT '0',
 `hits-year` int(11) UNSIGNED NOT NULL DEFAULT '0',
 `expires` int(11) UNSIGNED NOT NULL DEFAULT '0',
 `created` int(11) UNSIGNED NOT NULL DEFAULT '0',
 `updated` int(11) UNSIGNED NOT NULL DEFAULT '0',
 `deleted` int(11) UNSIGNED NOT NULL DEFAULT '0',
 PRIMARY KEY (`id`),
 KEY `directors_domain_jump_idx` (`domain-id`,`jump-id`,`api-uid`),
 KEY `directors_referee_domain_jump_uid_idx` (`referee`,`domain-id`,`jump-id`,`api-uid`),
 KEY `directors_chronologistics_idx` (`hits-last`,`hits-previous`,`expires`,`created`,`updated`,`deleted`),
 KEY `directors_statistician_idx` (`hour-start`,`hour-ended`,`week-start`,`week-ended`,`fortnight-start`,`fortnight-ended`,`month-start`,`month-ended`,`quarter-start`,`quarter-ended`,`year-start`,`year-ended`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

