DROP TABLE `locals`;

CREATE TABLE `locals` (
  `id` mediumint(128) UNSIGNED NOT NULL AUTO_INCREMENT,
  `modal` enum('jump','director','ip','tld','other') NOT NULL DEFAULT 'other',
  `domain-id` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `jump-id` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `director-id` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `tld-id` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `ip-id` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `other-id` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `country-id` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `state-id` int(128) UNSIGNED NOT NULL DEFAULT '0',
  `place-id` int(250) UNSIGNED NOT NULL DEFAULT '0',
  `longitude` decimal(16,12) NOT NULL  DEFAULT '0.000000000000',
  `latitude` decimal(16,12) NOT NULL  DEFAULT '0.000000000000',
  `hour-start` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `hour-ended` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `day-start` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `day-ended` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `week-start` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `week-ended` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `fortnight-start` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `fortnight-ended` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `month-start` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `month-ended` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `quarter-start` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `quarter-ended` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `year-start` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `year-ended` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `hits-total` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `hits-last` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `hits-previous` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `hits-oftern` float(21,10) UNSIGNED NOT NULL DEFAULT '0',
  `hits-hour` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `hits-day` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `hits-week` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `hits-fortnight` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `hits-month` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `hits-quarter` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `hits-year` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `created` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `updated` int(11) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `locals_index` (`modal`,`domain-id`,`jump-id`,`director-id`,`tld-id`,`ip-id`,`other-id`,`country-id`,`state-id`,`suburb-id`),
  KEY `locals_search` (`longitude`,`latitude`,`places-key`),
  KEY `locals_statistician_idx` (`hour-start`,`hour-ended`,`week-start`,`week-ended`,`fortnight-start`,`fortnight-ended`,`month-start`,`month-ended`,`quarter-start`,`quarter-ended`,`year-start`,`year-ended`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

