DROP TABLE `locals_countries`;

CREATE TABLE `locals_countries` (
  `id` mediumint(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `country` varchar(200) NOT NULL  DEFAULT '',
  `iso2` varchar(2) NOT NULL  DEFAULT '',
  `iso3` varchar(3) NOT NULL  DEFAULT '',
  `currency` varchar(3) NOT NULL  DEFAULT '',
  `nationality` varchar(3) NOT NULL  DEFAULT '',
  `places-key` varchar(64) NOT NULL  DEFAULT '',
  `longitude` decimal(16,12) NOT NULL  DEFAULT '0.000000000000',
  `latitude` decimal(16,12) NOT NULL  DEFAULT '0.000000000000',
  `min-longitude` decimal(16,12) NOT NULL  DEFAULT '0.000000000000',
  `min-latitude` decimal(16,12) NOT NULL  DEFAULT '0.000000000000',
  `max-longitude` decimal(16,12) NOT NULL  DEFAULT '0.000000000000',
  `max-latitude` decimal(16,12) NOT NULL  DEFAULT '0.000000000000',
  `hour-start` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `hour-ended` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `day-start` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `day-ended` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `week-start` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `week-ended` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `fortnight-start` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `fortnight-ended` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `month-start` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `month-ended` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `quarter-start` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `quarter-ended` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `year-start` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `year-ended` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `hits-total` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `hits-last` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `hits-previous` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `hits-oftern` float(21,10) UNSIGNED NOT NULL DEFAULT '0',
  `hits-hour` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `hits-day` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `hits-week` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `hits-fortnight` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `hits-month` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `hits-quarter` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `hits-year` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `created` int(11) UNSIGNED NOT NULL DEFAULT '0',
  `updated` int(11) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `countries_index` (`country`,`iso2`,`iso3`,`currency`,`nationality`),
  KEY `countries_search` (`longitude`,`latitude`,`places-key`),
  KEY `countries_statistician_idx` (`hour-start`,`hour-ended`,`week-start`,`week-ended`,`fortnight-start`,`fortnight-ended`,`month-start`,`month-ended`,`quarter-start`,`quarter-ended`,`year-start`,`year-ended`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

